version: '3.9'

services:
  pokedexapi_prod:
    depends_on:
      - mongo_db_prod
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker-prod
    container_name: pokedexapiprod
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '${PORT}:${PORT}'
    environment:
      MONGODB: ${MONGO_URL}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    networks:
      - nestjs-network-prod

  mongo_db_prod:
    image: mongo:5
    container_name: mongo_db_nest_pokemon_prod
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=nest-pokedemon
    volumes:
      - mongopokedexprod:/data/configdb
      - mongopokedexprod:/data/db
    networks:
      - nestjs-network-prod

networks:
  nestjs-network-prod:
    name: nestjs-network-prod
    driver: bridge

volumes:
  mongopokedexprod: {}
